import lookbook from './lookbook.json';
import { stackImages } from './gallery-layout';

export type GalleryImage = { src: string; width: number; height: number; group: number };
export type Photo = { src: string; width: number; height: number };

// Landing hero, from the "Website 2.0 Outline" line sheet: lookbook frame 1345
// on desktop and 1790 on phones, downscaled from the originals into public/home.
export const HERO_IMAGE: Photo = { src: '/home/hero-desktop.jpg', width: 3200, height: 2560 };
export const HERO_IMAGE_MOBILE: Photo = { src: '/home/hero-mobile.jpg', width: 1600, height: 2000 };

// The lookbook shoot, one image per frame in shoot order. Generated by
// `npm run import:lookbook -- <folder>`; do not hand-edit lib/lookbook.json.
export const GALLERY_IMAGES: GalleryImage[] = lookbook.images;

// The same frames collapsed into one tile per set of similar shots.
export const GALLERY_STACKS = stackImages(GALLERY_IMAGES);

// Newsletter modal picture: lookbook frame 1012 per the line sheet, falling
// back to the first portrait frame if that frame is ever dropped from the shoot.
export const NEWSLETTER_IMAGE: Photo =
  GALLERY_IMAGES.find((g) => g.src.endsWith('/1012.jpg')) ??
  GALLERY_IMAGES.find((g) => g.height > g.width) ??
  GALLERY_IMAGES[0];
